### PR TITLE
add-eaglesight02.mdx

### PR DESCRIPTION
**Pull request by Eaglesight02**

### CODE REVIEW

**Comment by Icarus131** [comment]
Please follow the required formatting for the mdx file

**Comment by Eaglesight02** [comment]
> Please follow the required formatting for the mdx file

Thanks for the feedback @Icarus131 ! Will go throught the MDX documentation and change the formatting.

**Comment by Eaglesight02** [comment]
Updated the eaglesight02.mdx file with the correct formatting changes.

**Comment by Eaglesight02** [comment]
Hey @Icarus131, I've done the required changes in the formatting. Do review it once :)

**Comment by Icarus131** [comment]
LGTM.Merging

**Comment by Eaglesight02** [comment]
> LGTM.Merging

Thank you @Icarus131 :)

**Pull request merged**
