### PR TITLE
added Ullas-g mdx

### PR DESCRIPTION
**Pull request by Ullasgsagar563**
my first pull requsted

### CODE REVIEW

**Comment by Ullasgsagar563** [comment]
fix #367

**Review by adithya-s-k — CHANGES_REQUESTED** [review]
Leave a space between name: and role:

```
---
name: Ullasa G
role: App Developer
semester: 5
---
```

**Comment by Ullasgsagar563** [comment]
Ok i will

**Comment by Ullasgsagar563** [comment]
i changed file fix #367

**Pull request merged**
