### PR TITLE
added suchir-m-v.mdx file

### PR DESCRIPTION
**Pull request by suchirmv-1524**
closing issue

### CODE REVIEW

**Comment by suchirmv-1524** [comment]
please can anyone help me out with these branch conflicts? I was promised a review into the issue but hasn't happened yet

**Comment by karthik2603-theBrogrammer** [comment]
remove your ds-store file

**Comment by suchirmv-1524** [comment]
Can you please help me how to remove it please

**Comment by suchirmv-1524** [comment]
Hey I have successfully added the pull request but it isn't showing on the
HackFest page

**Pull request merged**
